services:
  moderne-connector:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/app/application.yml:ro
      - ./example-repos.csv:/app/repos.csv:ro
    restart: unless-stopped
