FROM eclipse-temurin:21-jdk

RUN groupadd -r app && useradd --no-log-init -r -m -g app app

WORKDIR /app

COPY --chown=app:app connector-*.jar /app/connector.jar

USER app

EXPOSE 8080

ENTRYPOINT ["java"]
CMD ["-XX:-OmitStackTraceInFastThrow", \
     "-XX:MaxRAMPercentage=65.0", \
     "-XX:MaxDirectMemorySize=2G", \
     "-XX:+HeapDumpOnOutOfMemoryError", \
     "-XX:+ExitOnOutOfMemoryError", \
     "-XX:+UseStringDeduplication", \
     "-jar", "/app/connector.jar"]
